### ISSUE TITLE
New skills to be added for card editing!

### ISSUE THREAD

**Issue by ElysiaSakura** [MagiCircles/CinderellaProducers#25]
Skill name: Skill Boost
Description: Every - seconds: there is a -% chance that currently active skills will be boosted for - seconds.
Example: https://starlight.kirara.ca/char/223#c_200377_head

**Comment by mashupdarkness** [comment]
Skill name: Cute Focus
Description: Every - seconds there is a -% chance that when there are only Cute idols on the team, you will gain an extra -% combo bonus, and Perfect notes will receive a -% score bonus for - seconds.
Example: https://starlight.kirara.ca/char/164#c_100371_head

**Comment by mashupdarkness** [comment]
Leader skill name: Cute Princess
Description: When there are only cute idols on the team, all appeal stats will be raised by -% for all idols.
Example: https://starlight.kirara.ca/char/164#c_100371_head

**Comment by mashupdarkness** [comment]
Also it might be safe to say that Cool and Passion versions of these skills and leader skills will appear in the future, so maybe it'd be a good idea to add them for now so we don't bombard them on you later.

**Comment by mashupdarkness** [comment]
Skill name: Passion Focus
Description: Every - seconds there is a -% chance that when there are only Passion idols on the team, you will gain an extra -% combo bonus, and Perfect notes will receive a -% score bonus for - seconds.

Leader skill name: Passion Princess
Description: When there are only Passion idols on the team, all appeal stats will be raised by -% for all idols.

Example: https://starlight.kirara.ca/char/247#c_300377_head

**Comment by mashupdarkness** [comment]
Skill name: Cool Focus
Description: Every - seconds there is a -% chance that when there are only Cool idols on the team, you will gain an extra -% combo bonus, and Perfect notes will receive a -% score bonus for - seconds.

Leader skill name: Cool Princess
Description: When there are only Cool idols on the team, all appeal stats will be raised by -% for all idols.

Posting for cool ahead of time since it'll be the same when it gets added in game.
