### ISSUE TITLE
Skills and Event to be added to options!

### ISSUE THREAD

**Issue by mashupdarkness** [MagiCircles/CinderellaProducers#28]
**New Skills:**

**Encore:** Every 12 seconds: there is a 40% chance to activate the previous skill again for 4 seconds.
https://starlight.kirara.ca/char/233#c_200481_head

**Life Sparkle:** Every 9 seconds: there is a 40% chance that you will gain an extra combo bonus based on your current health for 4 seconds.
https://starlight.kirara.ca/char/108#c_100481_head

**Tricolor Synergy**: Every 11 seconds: there is a 40% chance that with all three types of idols on the team, you will gain an extra 15% combo bonus, and Perfect notes will receive a 16% score bonus plus restore 1 HP, for 5 seconds.
https://starlight.kirara.ca/char/126#c_100499_head
(Looks like we'll need another skill value space for this skill)

**New Leader Skills:**

**Cute, Cool, Passion Princess:** Raises all appeals of all Cute/Cool/Passion members by 50% when there are only Cute/Cool/Passion idols on the team.
https://starlight.kirara.ca/char/101#c_100447_head
https://starlight.kirara.ca/char/167#c_200399_head
https://starlight.kirara.ca/char/234#c_300457_head
(So new idea. Instead of drop down, put a new checkbox beside leader skill all that says leader skill same type. the reason why this needs to be separate because if left alone it makes the leader skill cute/cool/passion brilliance. checking the box then would make the leader skill type the new focus skill)

**Fortune Present:** Gives extra rewards when you finish a live.
https://starlight.kirara.ca/char/233#c_200481_head
(This could be added as Present in the Leader Skill Type drop-down)

**Cute/Cool/Passion Cheer:** Raises the life of all Cute/Cool/Passion members by 40% when there are only Cute/Cool/Passion idols on the team.
https://starlight.kirara.ca/char/108#c_100481_head
(Select Leader Skill Type: Life, then check leader skill same type)

**Cinderella Charm**: Increases fan gain by 30% when you finish a live.
https://starlight.kirara.ca/char/126#c_100499_head
(Can be listed as Fans in leader skill drop down)

**New Event**

ススメ ! シンデレラロード (Go Forward! Cinderella Road)

**Comment by Squishy3000** [comment]
here's the JP strings for these skills

Encore - ⎾(CHANCE)%の確率⏌ (TIME)秒毎、高確率で少しの間、直前に発動した他アイドルの特技効果を繰り返す

Life Sparkle - ⎾(CHANCE)%の確率 - (DURATION)秒⏌ (TIME)秒毎、高確率で少しの間、ライフ値が多いほどCOMBOボーナスアップ

Tricolor Synergy - ⎾(CHANCE)%の確率 - (DURATION)秒⏌ 3タイプ全てのアイドル編成時、(TIME)秒毎、高確率でしばらくの間、PERFECTのスコア(STRENGTH1)%アップ/ライフ(STRENGTH2)回復、COMBOボーナス(STRENGTH3)%アップ
Note: Since it's unlikely that there will ever be a tricolor synergy card that gives more than 1 life per note, that could be set as a constant. The string would then be:
⎾(CHANCE)%の確率 - (DURATION)秒⏌ 3タイプ全てのアイドル編成時、(TIME)秒毎、高確率でしばらくの間、PERFECTのスコア(STRENGTH1)%アップ/ライフ1回復、COMBOボーナス(STRENGTH2)%アップ

Cute/Cool/Passion Princess - (TYPE)アイドルのみ編成時、全員の全アピール値(STRENGTH)%アップ

Fortune Present - LIVEクリア後、特別報酬を追加で獲得 (there are no parameters for this one)

Cool/Cute/Passion Cheer - (TYPE)アイドルのみ編成時、全員のライフ(STRENGTH)%アップ

Cinderella Charm - LIVEクリア時、獲得ファン数が(STRENGTH)%アップ
